spring: 
  application:
    name: cloud-gateway 
  cloud:
    gateway:
      routes:
      # 路由的ID，没有固定规则但要求唯一，建议配合服务名
      - id: config_route
      	# 匹配后提供服务的路由地址
        uri: http://ityouknow.com
        # 断言，路径相匹配的条件
        predicates:
        - Path=/routeconfig/rest/**
      - id: header_route
        uri: http://ityouknow.com
        predicates:
        - Header=X-Request-Id, \d+
